

service: spacy-api

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1


package:
#  include:
#    - include-me.py
#    - include-me-dir/**
  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**
    - node_modules/**
    - .vscode/**
    - __pycache__
    - .ipynb_checkpoints/**
    - (*).ipynb

functions:
  get-dep:
    handler: handler.handle_request
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: spacyapi
          method: post


custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    zip: true
    noDeploy: []
    useDownloadCache: true
    # useStaticCache: true

plugins:
  - serverless-python-requirements
